#MySQL
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/ssmManager?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true
jdbc.username=root
jdbc.password=root

# update: 返回值为匹配数据库的条数,通过对 JDBC URL 显式的指定 useAffectedRows 选项，我们将可以得到受影响的记录的条数